dist: trusty
sudo: required
language: java
jdk:
- openjdk8
script:
- cd spec-publisher
- mvn clean package
- java -jar target/mets-profile-proc.jar ../profile/E-ARK-SIP.xml
- cd ..
- docker run -it --rm -v "$PWD:/source" -u "$(id -u):$(id -g)" --entrypoint /source/create-site.sh eark4all/spec-pdf-publisher
- cd spec-publisher
- git stash
- git checkout feat/pdf-publication
- mvn clean package
- java -jar target/mets-profile-proc.jar ../profile/E-ARK-CSIP.xml
- cd ..
- docker run -it --rm -v "$PWD:/source" -u "$(id -u):$(id -g)" --entrypoint /source/create-pdf.sh eark4all/spec-pdf-publisher
- bundle install
- bundle exec jekyll build -s ./docs -d ./_site
- bundle exec htmlproofer ./_site --file-ignore /javadoc/ --only-4xx --check-html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GH_TOKEN"
  keep_history: true
  local_dir: docs
  fqdn: earksip.dilcis.eu
  on:
    branch: master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: BjL+RmPgmCs4FkKlHCA2W2EkMdqRdQl7GF4hT2oeyUgvzGx5jJ5mU1E5ffKFj/xYGZiMqdW7kkXaNDYiJ0ouzsi8+WOEi7TcFkFBVdMkDkwoIJp5iBhSPqMe1/+0umJr6nUggwPAAgf2z3jbQDOlB4wj2Pm71hTwZqceb2Ifhb3p1KDfb8b61vpoYsirqd2ANn3M1xMViDyjHBwEhPPFO/x5CU66g+RklczwIanvvx/W4RVd/bigsrlSgcjDtXDZj+kbLvwraUJxrnLFpq9cHimSdrmGw1tCWtSlfKWVXM4FLwCZnaKXQgsABqAaJkwCBepjQOC3zPYBxl7rzWg10GKyZa4DB5RjSnw96YCHjlMTLoWFQ9V0EJZb/dUDa6pG3aElNYGBIsPrrlUXKOa1ID0iSn0LxUxLYTGo8ikan/LH2zaXtXUaIK5kUVRo8f9JqgY9+iS+6IkTfSxwVIqkr7YN3f+ldCIqKaT6CynaYzu32v7BMQBPHZlDRiSiWyyG74O2uLBh3FyGZk2FZWuK8SAaHvntKrLo3rlsQYEl32UILzlpGYQvrQGCQzbqzW4B4BzsUkp9YUUPqWTXfjpm0fhkCnhbwPe3Bwho26hFptUKg9SUmfooqZ4rP0UGLtI5al2u5YFI+5vXV3j9BqbEAFBzcUew2Bdt9z1OpPDyh9o=
