[chapter]
= METS

The Metadata Encoding and Transmission Standard (METS) is a standard for encoding descriptive, administrative, and structural metadata expressed using the XML Schema Language.

METS schema is utilized across the various types of packages (SIP, AIP and DIP) maintaining a consistent approach to metadata encoding anda data structuring. The specific application of the METS schema within an E-ARK packages is detailed in the Common Specification for Information Packages (CSIP), particularly in section "5.3 Use of METS". This section outlines how METS should be implemented, including the precise requirements for its use within the E-ARK information packages.

Although the METS schema serves as a common foundation for SIPs, AIPs, and DIPs within E-ARK information packages, there are subtle differences in its application across these packages. These variations are mainly in the customization of attribute values, the definition of controlled vocabularies, and the adjustment of element optionality - transforming some optional elements into mandatory ones. Such adjustments ensure that the METS schema is optimally tailored to meet the specific needs of each package type, enhancing the precision and utility of metadata encoding for digital preservation and access.

The specific differences between the METS instances for SIP and the Common Specification for Information Packages (CSIP) are articulated through what is known as a METS profile. A METS profile is a detailed document that defines how the METS schema is adapted or extended for particular use cases or types of digital packages. In this context, the SIP METS profile is an extension of the more general CSIP METS profile, focusing on the particular requirements and adaptations necessary for Submission Information Packages within the E-ARK Information Packages framework.

== Extended use of the METS root element (element `mets`)

The root element of a METS document `<mets>` can contain a number of optional attributes, namespaces (`xmlns:`), locations for external schemas (`xsi:`) and a number of other elements.

The following table describes the differences in the `<mets>` element between the E-ARK SIP and the `<mets>` element of a Common Specification for Information Packages (CSIP).

include::tables/metadata-root-requirements.adoc[]

== Extended use of the METS header (element `metsHdr`)

The `<metsHdr>` (METS header) element is a crucial part of the METS schema, providing metadata about the creation and management of the Submission Information Package (SIP). This element encapsulates information about various actors involved in the creation, preparation, and submission of the SIP. These actors are referred to as "agents" and are represented within the METS file by the `<agent>` element, which is nested within the `<metsHdr>` element.

This must not be confused with agents responsible for creating or contributing to the intellectual content carried within the SIP. Those contributors shall be documented in the descriptive metadata, also included in the package.

=== Agents, roles and types

The Common Specification for Information Packages (CSIP) requires that every Information Package (IP) includes at least one `<agent>` element to identify the software used to create the package. This is defined in CSIP requirements 10 to 16.

In addition, the `mets/metsHdr/agent` element may be used to document organisations and individuals involved in the creation or submission of the SIP to an OAIS. Each agent must include its name, role, and type, and may also contain further contextual information if relevant.

This approach supports accountability and transparency in the SIP creation processes and assists the OAIS in providing feedback to producers during ingest, for example, by identifying issues in the SIP that may need correction or clarification.

The SIP specification enables implementers to describe several additional agents under the `mets/metsHdr` element. Each agent must have a distinct role (`mets/metsHdr/agent/@ROLE`). Options available for the `@ROLE` attribute include:

* *CREATOR* - The person or institution responsible for the creation of Submission Information Package.
* *EDITOR* - The person or institution responsible for preparing the metadata included in the Submission Information Package.
* *ARCHIVIST* - The person or institution responsible for the document/collection
* *PRESERVATION* - The person or institution responsible for preservation functions.
* *CUSTODIAN* - The person or institution charged with the oversight of a document/collection.
* *IPOWNER* - Intellectual Property Owner - The person or institution holding copyright, trade or service marks or other intellectual property rights for the object.
* *OTHER* - None of the preceding values encompasses the role of the agent. When OTHER is used one must set the OTHERROLE attribute.

Each `mets/metsHdr/agent` element may also have a type (`mets/metsHdr/agent/@TYPE`). The type of agent must be set to one of the following values:

* *INDIVIDUAL* - The agent is an individual person.
* *ORGANIZATION* - The agent is an institution, corporate body, association, non-profit enterprise, government, religious body, etc.
* *OTHER* - None of the preceding values encompasses the type of the agent with clarity. When OTHER is used one must set the OTHERTYPE attribute.

Please note that the SIP must include information about the agent that has submitted the SIP to the OAIS. This shall be encoded as follows:

[,xml]
----
<agent ROLE="OTHER" OTHERROLE="SUBMITTER" TYPE="ORGANIZATION">
    <name>Office of Personnel Management</name>
    <note csip:NOTETYPE="IDENTIFICATIONCODE">VAT:12443112345-A357</note>
</agent>
----

=== Package status

The `<metsHdr>` element may also be used to indicate the expected behaviour of the OAIS while processing a given SIP. For example, it is possible to signal that a SIP is intended to replace an existing AIP in the repository by setting `mets/metsHdr/@RECORDSTATUS="REPLACEMENT"`, or to indicate that a SIP is submitted for testing purposes only, in which case no AIP should be created (`@RECORDSTATUS="TEST"`). `</metsHdr>`

The complete list of values admissible for the `@RECORDSTATUS` attribute are:

* *NEW* - The SIP constitutes a new submission not previously delivered to the repository.
* *SUPPLEMENT* -- The SIP supplements a previous submission by adding new or complementary information.
* *REPLACEMENT* - The SIP fully replaces a previous submission, typically correcting or updating its content.
* *TEST* - The SIP is submitted for testing purposes only and must not result in the creation of an AIP.
* *VERSION* - The SIP contains the same set of content files as a previous submission, but includes one or more files with updated versions.
* *DELETE* -- A request from the Producer for the OAIS to delete an existing AIP from the repository.
* *OTHER* - The SIP has a status that does not match any of the predefined values in this vocabulary.

See the `Package status` vocabulary (`@RECORDSTATUS`) for further details.

=== Submission agreement

The metsHdr element also provides a mechanism to identify the Submission Agreement that governs the creation of a given SIP. This is achieved using the `altRecordID` element with the attribute `mets/metsHdr/altRecordID/@TYPE="SUBMISSIONAGREEMENT"`. Declaring the applicable Submission Agreement ensures that the SIP can be validated against a known set of rules agreed between the Producer and the OAIS.

The table below outlines the key extensions in the use of the `mets/metsHdr` element between the E-ARK SIP and the Common Specification for Information Packages (CSIP).

=== Key extensions to the metsHdr element

include::tables/metadata-metshdr-requirements.adoc[]

== Extended use of the METS descriptive metadata section (element `dmdSec`)

The METS descriptive metadata section `<dmdSec>` is responsible for recording descriptive metadata for all the data items included in the package.

The SIP specification itself does not prescribe of any particular metadata format. It is a role of the OAIS together with the Producer to set the rules in terms of descriptive metadata. These rules should be set and agreed upon in the `Submission Agreement`.

In the context of the `<dmdSec>` element, the SIP specification does not change or extend any of the requirements already defined by the Common Specification for Information Packages (for more information see section 5.3.3 of the CSIP).

== Extended use of METS administrative metadata section (element `amdSec`)

The `<amdSec>` (administrative metadata section) in a METS document plays a crucial role in encapsulating or referencing the technical and preservation metadata related to a digital object or collection. This section is pivotal for maintaining the integrity, understanding, and long-term preservation of digital resources.

Preservation metadata, while not always found within Submission Information Packages, holds significant value, especially in recording the history of events affecting the state and stewardship of the information package. Preservation metadata is primarily associated with activities undertaken after a package's ingestion into a digital repository. However, certain preservation events, such as the digitization of analog materials, may occur prior to ingest and are thus relevant for inclusion within an SIP. Documenting such pre-ingest preservation activities provides a comprehensive record of the efforts taken to convert, preserve, and prepare digital objects for archiving and future access.

The https://www.loc.gov/standards/premis/premis-mets.html[Using PREMIS with METS guide] by the Library of Congress offers detailed recommendations on how to effectively incorporate PREMIS metadata within a METS document, ensuring that vital preservation details are accurately represented and accessible.

In the context of `<amdSec>`, the SIP specification does not change or extend any of the requirements already defined by the Common Specification for Information Packages (for more information see section 5.3.4 of the CSIP).

== Extended use of the METS file section (element `fileSec`)

The METS file section element `<fileSec>` is used to describe all the components included in the information package which have not been already included in the `<amdSec>` and `<dmdSec>` elements.

The main purpose of the METS `<filSec>` element is to serve as a "table of contents" or "manifest" for all the files included in the package, thus allowing the OAIS to validate the integrity and completeness of the files that are part of the package.

This means that the location and checksum of all the files that compose the SIP must be enlisted within the `<fileSec>` element. This includes files in the `data`, `schemas` and in the `documentation` folders.

The following table describes the differences in the `<fileSec>` between an E-ARK SIP and the CSIP.

include::tables/metadata-filesec-requirements.adoc[]

== Extended use of the METS structural map (element `structMap`)

The mandatory METS structural map element `<structMap>` is intended to provide an overview of the components included in the package. It can also link elements of that structure to associated content files and metadata. In the CSIP the `structMap` describes the higher-level structure of all the content in the root and may link to existing representations.

In the context of `<structMap>`, the SIP specification does not change or extend any of the requirements defined by the Common Specification for Information Packages (for more information see section 5.3.6 of the CSIP)
